---
# tasks file for ha-proxy
- name: http
  package:
    name: httpie
    state: present

- name: install HAProxy
  yum:
    name: haproxy
    state: present

- name: enable HAProxy
  service:
    name: haproxy
    state: started

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: [Restart HAproxy]
