---
# tasks file for postgres
- name: install postgres
  yum:
    name: postgresql-server
    state: present
  notify: [Initialize DB]

- name: enable apache at boot
  service:
    name: postgresql
    enabled: true
    state: started
